/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sumatoria;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void sumatoriaCasoPositivo() {
        assertTrue( Sumatoria.calcular(3) == 6 );
    }
    
    @Test( expected = ArithmeticException.class )
    public void sumatoriaCasoNegativos() {
    	Sumatoria.calcular(-3);
    }
    
    @Test public void casoEspecialCero() {
    	assertTrue( Sumatoria.calcular(0) == 0);
    }
    
    @Test public void casoEspecialUno() {
    	assertTrue( Sumatoria.calcular(1) == 1);
    }
    
}
