/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sumatoria;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void sumatoriaCasoPositivo() {
        assertTrue( Sumatoria.calcular(3) == 6 );
    }
}
